### ISSUE TITLE
[комиссия по этике] нужна кнопка "завершить игру"

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#102]
![изображение](https://user-images.githubusercontent.com/51483087/79472200-34adf500-800c-11ea-9625-d4eff299ef08.png)
Сейчас игру закончить можно, только перейдя опять по ссылке. Надо это исправить.

**Comment by DenMesh** [comment]
Я правильно понимаю, что имеется в виду возможность завершить игру досрочно? Также не понял, по какой ссылке надо опять переходить.

**Comment by kupaeva** [comment]
Имею в виду, что сейчас для того, чтобы начать новую игру, надо открыть исходную страницу начала игры http://stemgames.ru/science/committee . 

Да, возможность завершить игру досрочно

**Comment by DenMesh** [comment]
Добавил кнопку завершения игры (появится на сайте после того, как будет закрыта эта тема). Кнопка *просто* переносит пользователя на название игры, не завершая предыдущую, так что если она нажата по ошибке, достаточно вернуться назад в браузере.
