### ISSUE TITLE
[комиссия по этике] таймер не работает и съезжает

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#104]
Таймер для проводящего есть на странице, но не понятно, как его настроить и включить. У детей на странице его нет. Может, убрать?
Тем более, что он при изменении размера экрана съезжает
![изображение](https://user-images.githubusercontent.com/51483087/79503895-9b4a0780-803a-11ea-8997-5add91b70a14.png)

**Comment by DenMesh** [comment]
Таймер убран.
