### ISSUE TITLE
[комиссия по этике] не обязательно! возможность регулировать порядок этапов 

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#106]
Это не важно, только в случае, если это не сложно. 
добавить возможность делать запуск без обучения, или с повторением создания проекта и его оценки.

**Comment by DenMesh** [comment]
Для этого придётся перестроить то, как обрабатываются данные. Сейчас всё довольно жёстко привязано к номеру хода. Закрываю без разрешения.
