### ISSUE TITLE
[диплом] добавить кнопку, по которой открывается ссылка и qr код входа в игру

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#107]
Сейчас после начала игры нет возможности вернуться туда обратно, если окошко закрылось. Это надо исправить. Можно и как-то иначе, но я предлагаю сделать страницу с qr и ссылкой, например, вот так: 
![изображение](https://user-images.githubusercontent.com/51483087/79638132-ac0a9280-818c-11ea-9acc-4f29ade43eb0.png)
![изображение](https://user-images.githubusercontent.com/51483087/79638208-18859180-818d-11ea-8a02-61df16a50a2a.png)
 (картинки очень грубые)

**Comment by everdina** [comment]
Кнопки
давайте у нас все-таки самая основная кнопка будет кнопкой, а все остальные ссылками, а то светофор)
Ссылки все слева и между ними "отбойник", чтобы не сливались (#AFAFAF)


![research-activity-v5-desktop-mobile3](https://user-images.githubusercontent.com/46641854/80308253-873e9c80-87d6-11ea-8694-c65405086f0c.jpg)

**Comment by everdina** [comment]
Еще на том же экране, когда студент ушел в академ.
Полоса, показывающая академ в таблице:

- Название команды не закрыто, все остальное закрыто rgba(0,0,0, 0.7).
- Надпись "Академический отпуск"  белая, выровнена вправо с отступом справа 24px (предполагаю, что она там будет лучше видна, потому что под ней контент не цветной, а то сейчас как-то все мешается)

**Comment by kupaeva** [comment]
Только текст нe QR, а "окно входа в игру", учитель может не знать слово QR
