### ISSUE TITLE
[диплом] добавить для проводящего галочки о том, отправила ли команда ход

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#108]
Проводящему нужна обратная связь, справилась ли команда с ходом. Галочки можно поставить слева от названия команды в списке, вот так: 
![изображение](https://user-images.githubusercontent.com/51483087/79638251-613d4a80-818d-11ea-8ef3-50b8f82abbd7.png)

**Comment by everdina** [comment]
Хорошее место для галочки, надо брать! Отступ только от нее до названия команды надо,  16px
А галочку из font-awesome <i class="fas fa-check"></i>
