### ISSUE TITLE
[диплом] Меняем интерфейс для участника

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#109]
Что изменилось: 
1) инфа о дедлайнах - наверху и выделена относительно всего остального
2) далее дублируется вся информация о прогрессе команды, включая шкалу отдыха. 

Дизайн нарисован мной на коленке, если надо красивую картинку, то надо просить Дину

![изображение](https://user-images.githubusercontent.com/51483087/79638992-6c927500-8191-11ea-8bbd-22cf3e4d5e78.png)

**Comment by kupaeva** [comment]
Далее: не очевидно, что в окошко можно ввести циферки. С другой стороны, + и - неудобные. Может, просто оставим окошко для ввода циферок? 
![изображение](https://user-images.githubusercontent.com/51483087/79639113-373a5700-8192-11ea-8616-5f9be5038837.png)

**Comment by kupaeva** [comment]
И надо писать актуальное дело и актуальный дедлайн( в общем, дублировать всю информацию для игроков по их команде.

**Comment by everdina** [comment]
По поводу ввода циферок: давайте оставим, надо проверить игроками, удобны они или нет (на мобильнике вообще цифры вводить с клавиатуры должно быть менее удобно, чем кнопками). 

По поводу результатов хода.
Предлагаю попробовать так.

Верх окна оставляем, только номер хода добавим, кнопку в середину двигаем.
Содержимое экрана - см картинку
Если команда за ход ничего не сделала, давайте писать там вместо данных команды "нет", а не просто пустоту
Поигралась с отступами и шрифтами, вроде должно все влезть: весь шрифт одинакового размера (16), выделение только цветами и болдом, как на картинке. Серый 787878 красный и зеленый - как в таблице .

![research-activity-v5-desktop-mobile1](https://user-images.githubusercontent.com/46641854/80308233-68400a80-87d6-11ea-8574-e0ec96548abe.jpg)

**Comment by kupaeva** [comment]
Тогда надо и на экране проектора писать процент отдыха (внутри шкалы, например), чтобы это было легко понимать.

**Comment by DenMesh** [comment]
Процент плох тем, что из него сложно получить цифру. Лучше что-то в духе "5/9"
