### ISSUE TITLE
[сайт] Правки к задаче #86

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#114]
Сделай, пожалуйста, иконки соц.сетей побольше и размести их по центру высоты, а саму высоту плашки меньше. 
![изображение](https://user-images.githubusercontent.com/51483087/80094051-42b0c800-856e-11ea-9db8-d7e57ee75f44.png)
вот этот образец все еще актуален.

![изображение](https://user-images.githubusercontent.com/51483087/80094093-552b0180-856e-11ea-87bd-3cfa10b6afd4.png)

**Comment by DenMesh** [comment]
То есть, местоположение убрать?23.04.2020, 14:26, "kupaeva" <notifications@github.com>:
Сделай, пожалуйста, иконки соц.сетей побольше и размести их по центру высоты, а саму высоту плашки меньше.

вот этот образец все еще актуален.

**Comment by kupaeva** [comment]
Высота плашки, размер иконок, расположение надписи.

**Comment by DenMesh** [comment]
Я имею в виду надпись "Москва" с иконкой. Её убрать или оставить?

**Comment by kupaeva** [comment]
Лучше убрать.
