### ISSUE TITLE
в этике нет кнопки "начать новую игру" или перейти куда-то

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#19]

**Comment by DenMesh** [comment]
Требуется уточнение  - где нет кнопки?19.08.2019, 15:34, "kupaeva" <notifications@github.com>:

**Comment by kupaeva** [comment]
после того, как ты закончил игру

пн, 19 авг. 2019 г. в 16:06, DenMesh <notifications@github.com>:
