### ISSUE TITLE
остров: карта в мобильной версии

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#27]
![изображение](https://user-images.githubusercontent.com/51483087/63790105-546b9e00-c901-11e9-98a3-583d14ff4037.png)

Карту приблизить можно, но двигать после этого не получается. То есть игрокам доступно только пол карты. 
вопроизвести: зайти с мобильного и приблизить.

**Comment by DenMesh** [comment]
Предположительно пофикшено.
