### ISSUE TITLE
остров: не переключается ход

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#28]
ход на компе и телефоне не синхронизуется. 
Зашла с телефона, выбрала гекс, нажала копать.
С компа нажала кнопку "переключить ход".
Номер хода изменился, гекс не раскопался, на телефоне - заставка "ожидание"

**Comment by DenMesh** [comment]
Закрываю - проблема с соединением вебсокета при использовании прокси.
