### ISSUE TITLE
ссылка на странице QR кода 

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#32]
на экране с QR кодами для команд есть соблазн жамкнуть на ссылку с названием команды, хотя это вариант запасной. Надо запасной вариант сделать менее явным. Предлагаю под названием команды сделать "Копировать ссылку для команды" - потому что ведущий все равно будет копировать и пересылать ссылку команде в случае невозможности работы с QR кодом

**Comment by DenMesh** [comment]
Закрываю - это страница больше не существует в описанном виде.
