### ISSUE TITLE
дизайн - выравнивание кнопки

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#34]
Кнопка сползла влево. Давай ее поставим по центру. Также сползли кнопки далее на всей этике-1, кроме первой страницы (начало игры) и страницы результатов. На результатах тоже сползли, но их надо расставить по краям, а не в середину.

![в-этике-все-кнопки-сползли-налево-давай-сделаем-по-центру](https://user-images.githubusercontent.com/46641854/64508952-5eb96f00-d2e7-11e9-8110-3318b18591c6.jpg)

**Comment by DenMesh** [comment]
У меня всё в порядке, что за браузер?

**Comment by everdina** [comment]
Google Chrome 
Version 76.0.3809.132 (Official Build) (64-bit)
на win 7 и на win 10 
на двух разных компах одинаково сползло

в Firefox посмотрела - там кнопки "Далее" нормально, но "Закончить игру" и в ФФ и в Хроме сползла одинаково

![сползшая кнопка](https://user-images.githubusercontent.com/46641854/64597725-fb027500-d3be-11e9-8e77-38eda297fc05.jpg)
