### ISSUE TITLE
дизайн - кнопку покрасить в неактивную, когда она неактивна

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#39]
в этике-1 на странице с номерами вопросов кнопка "Далее" выглядит как активная, но не нажимается, когда не выбран никакой вопрос. Должна выглядеть как неактивная, так как ее нельзя нажать, пока не выберешь вопрос и ответ.

**Comment by DenMesh** [comment]
Не могу воспроизвести: у меня кнопка выглядит неактивной так, как положено. Возможно, слишком похожие друг на друга стили?

![image](https://user-images.githubusercontent.com/9051037/64535745-7a8d3700-d320-11e9-9911-10c5ebb428d9.png)
![image](https://user-images.githubusercontent.com/9051037/64535757-80831800-d320-11e9-963c-99a1f0bdaaac.png)

**Comment by everdina** [comment]
попробовала на другом компе - кнопка неактивная, все верно. Проверю завтра на рабочем, покажу тебе, если оно еще там)

**Comment by everdina** [comment]
а нет, баг какой-то плавающий, видимо. Немного пощелкала этику и снова она активная сначала. Для сравнения справа - неактивная (точно не стили слишком похожи)
![неактивная-кнопка](https://user-images.githubusercontent.com/46641854/64597065-bfb37680-d3bd-11e9-9df2-3ccc9d93ea9f.jpg)
