### ISSUE TITLE
все ломается на 4-м ходу

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#44]
На 4-м ходу:
справа есть окошко выбора гипотез.
![изображение](https://user-images.githubusercontent.com/51483087/65428492-23598d00-de1d-11e9-9958-8f074ea3fcec.png)
иногда сразу не грузится, иногда после обновления, не получается выбрать гекс
Список гипотез может быть пустым. 
Какое-то сочетание тапов выкидывает обратно на окно создания команды.

**Comment by DenMesh** [comment]
Предположительно исправлено.
