### ISSUE TITLE
пока команда тупит, нельзя продолжить игру

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#45]
![изображение](https://user-images.githubusercontent.com/51483087/65439262-8f44f100-de2f-11e9-9f2a-0978507a43c3.png)

Обсуждали, что у учителя должна быть возможность переключить ход, даже если команда ничего не сделала. Сейчас нельзя. Можно ли это исправить?

**Comment by DenMesh** [comment]
Исправлено
