### ISSUE TITLE
Диплом: настройки таймера

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#50]
1) Переименовать пункт "2. Выберите настройки таймера" в "2. Выберите продолжительность игры"
2) сделать пунктом по-умолчанию "игра на 30 минут"
3) пункт "таймер выключен" поставить последним
4) "Длительность хода задается вручную" перенести в "Показать расширенные настройки"

**Comment by DenMesh** [comment]
Более не актуально
