### ISSUE TITLE
Второе выдвижение гипотезы ломается, если первая была неполная

### ISSUE THREAD

**Issue by micrasterias** [DenMesh/stem-project-issues#54]
![image](https://user-images.githubusercontent.com/43093989/66137035-20248500-e605-11e9-9c18-2134b6569b89.png)

Если в первый раз гипотеза верная, но неполная (выделить 1 или 2 гекса), то если во второй раз все сделать правильно (выделить все три гекса), то гипотеза станет неверной.

**Comment by DenMesh** [comment]
При этом, если выбрать *только* недостающие гексы, гипотеза засчитывается как дополнение. Перенаправляю вопрос автору игры.
