### ISSUE TITLE
[Комиссия] Кнопки на мобильной и десктопной версии

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#62]
Так как это одни и те же кнопки, но экраны моб и десктопа очень разные, получается странно и там, и там. На мобильной кнопки получатся слишком маленькими, и расстояние между ними маленькое - трудно по ним попасть, а на десктопной широкие и стремные наоборот. Можно их по-разному для десктопа и моб показывать?

**Comment by DenMesh** [comment]
Можешь уточнить, о каких кнопках речь? Если это те, которые внизу экрана в игроцком интерфейсе, то я удивлён - они вроде должны быть большими и на всю ширину экрана, этого мало?19.11.2019, 13:13, "everdina" <notifications@github.com>:Так как это одни и те же кнопки, но экраны моб и десктопа очень разные, получается странно и там и там. На мобильной кнопки получатся слишком маленькими и расстояние между ними маленькое - трудно по ним попасть, а на десктопной широкие и стремные наоборот. Можно их по-разному для десктопа и моб показывать?

**Comment by everdina** [comment]
вот понимаешь, когда они на десктопе во всю ширину это странно, а на мобиле не хватает высоты и расстояния между ними. Вот соорудила стремный коллаж для прояснения)))
![collage](https://user-images.githubusercontent.com/46641854/69163928-219c0500-0b00-11ea-8b18-8b79300e5d45.jpg)
