### ISSUE TITLE
Этика: шрифт

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#63]
Это не очень важно
Но проблема с шрифтом такая: на компьютере в 100% он огромный, при этом на смартфоне - крохотный. 
![изображение](https://user-images.githubusercontent.com/51483087/69242632-536da400-0bb2-11ea-9204-363d7f77349b.png)
![2019-11-20_16-23-43](https://user-images.githubusercontent.com/51483087/69242639-57012b00-0bb2-11ea-9219-3c89db2e09d0.png)

**Comment by DenMesh** [comment]
(Заметка для себя) Проблема возникает на мобильниках с нецензурно большой плотностью пикселей. В результате бутстраповские медиа-запросы считают, что это нормальный широкий экран и ведут себя соответствующе. Посмотреть, как бороться с мобильниками.

**Comment by DenMesh** [comment]
@kupaeva , посмотри, пожалуйста, как оно выглядит сейчас. Есть шанс, что мне удалось это пофиксить, но проверить я не могу.

**Comment by DenMesh** [comment]
Считаю вопрос закрытым.
