### ISSUE TITLE
Этика: ссылка на правила разных членов комиссии

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#67]
Ссылка на правила должна быть доступна после того, как нажал "далее". Где она должна быть - лучше спросить Дину

**Comment by DenMesh** [comment]
@everdina , призыв в тему

**Comment by everdina** [comment]
Поскольку по идее открыть правила игроки должны были на экране с "Далее", а на следующем экране нужен только "запасной ход" к правилам, на случай если их закрыли случайно или протупили, то предлагаю рядом с ролью эту ссылку и поставить. Типа "Юрист (_правила для юриста_)"

И вот что - по этому случаю верхняя полоса тоже шире по вертикали требуется на мобиле!.. кстати, если будешь в эту пятницу в офисе, можем подробно причесать все эти ширины и высоты всего.
