### ISSUE TITLE
Этика: окончание игры

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#69]
Результаты должны быть доступны после того, как все проголосовали. Сейчас надо, чтобы каждый дополнительно нажал кнопку "далее".

**Comment by DenMesh** [comment]
Тогда получается, что последний проголосовавший может не успеть посмотреть, он накосячил или нет. Он голосует, у проводящего высвечивается, что все готовы, проводящий заканчивает игру.

**Comment by kupaeva** [comment]
Тогда у проводящего должна быть возможность закончить игру вне зависимости от того, все ли нажали "далее". 
То же самое с переключением ходов: сейчас игроки могут блокировать игру.
