### ISSUE TITLE
Поправить переходы после логина

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#7]
1) если кнопку "Перейти к курсу" кликает незалогиненный пользователь, то надо выдавать ему форму логина

2) когда человек залогинился, перекидывать его на стр списка блоков

**Comment by DenMesh** [comment]
Насчёт пункта 2: что если пользователь перешёл по сохранённой ссылке (например, на конкретный блок)? Логичнее показать ему окно логина, а потом перенаправить туда, куда он хотел попасть.

**Comment by everdina** [comment]
Да, точно, ты прав! Но когда он логинится с главной - то лучше на стр списка блоков, а не кидать обратно на главную, а то ему будет не сразу понятно, что произошло.
