### ISSUE TITLE
Этика: чуть поехала последняя страница

### ISSUE THREAD

**Issue by kupaeva** [DenMesh/stem-project-issues#70]
Чуть-чуть разъехалась последняя плашка. 
![изображение](https://user-images.githubusercontent.com/51483087/69255073-3d6ade00-0bc8-11ea-9d0f-20f13be8a042.png)

**Comment by DenMesh** [comment]
Ок, это начинает быть проблемой. @everdina, можешь подумать, как должен выглядеть этот заголовок? Это **глобальный** вопрос, не только к комиссии.

Проблема вот в чём: если экран достаточно широкий, то иконка (голубой квадратик), название ("Образовательная игра ...") и логотип СТЕМ идут на одной строчке. Иконка прижимается к левому краю, название - к иконке, логотип - к правому краю. Проблемы начинаются тогда, когда ширина экрана становится меньше, чем суммарная ширина их всех + отступы.

Прежде, чем я начну корячиться и верстать эту шапку, мне хочется знать, как оно должно правильно выглядеть. На текущий момент (за вычетом багов вёрстки) при уменьшении ширины экрана название переносится на строчку ниже, иконка и логотип остаются на месте.

**Comment by everdina** [comment]
Мое предложение такое:
	

- 	шапке заодно сделаем немного редизайн по цветам;
- 	лого стем немножечко поскромнее))) и на мобильниках вообще убирать;
- 	размер названия поменьше 1.25rem думаю ок;

- 	и да, край иконки надо выровнять с крайем контента слева, а то смотрится как сползшее.

	
	в остальном, как на картинке
	
![изменения-в-шапку](https://user-images.githubusercontent.com/46641854/69797801-651dff80-11e1-11ea-88d8-7a8fbb81b26c.jpg)

	
	@kupaeva , @DenMesh что думаете?

**Comment by DenMesh** [comment]
Мне кажется, надо как-то сделать контрастнее логотип СТЕМ. Ещё на мобильной версии как-то ... несбалансированно выглядит, что ли. Может быть, это я заморачиваюсь.

**Comment by DenMesh** [comment]
Нет, отмена про несбалансированность, я ещё немного посмотрел)

**Comment by everdina** [comment]
Повтыкала на логотип, задумка как раз была, что он и должен быть не слишком бросающимся в глаза. Как 25й кадр :)) Но сделала несколько посветлее.

![stem-logo-bluish](https://user-images.githubusercontent.com/46641854/69856980-ec31ad00-129f-11ea-89d4-0ea21b73872f.png)

**Comment by DenMesh** [comment]
Исправлено.
