### ISSUE TITLE
дизайн: сборник правок

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#71]
1. Выравнивание настроек опять сползло((( (см скриншот 1)

2. Нужны отступы 40 px сверху и снизу кнопок и сообщений на их месте типа "Проект отправляет капитан вашей команды." и итогов оценки проекта.

3. Сообщения на месте кнопок типа "Проект отправляет капитан вашей команды."  - цветом неактивной кнопки color: #7e9abe;

4. Слишком длинные кнопки на десктопах: "Войти", "Далее", на экране где "Теперь вы - общественный деятель из комиссии по ...".

5. Название профессии выделить - больше шрифт и по центру (как в макете или больше).

6. Таблица доп инфо на странице "Вы заняли такое-то место!" выглядит разползшейся, надо ее в полтора-два раза по горизонтали ужать.

7. Время от времени, примерно каждое пятое создание команд, у меня съзжает QR. Почему - отследить не удается( См скриншот 2

8. до кучи - текст подправить на стр 2 этапа
"Ниже исследование, направленное вам на оценку. Галочками помечены детали, которые выбрали исследователи. Просмотрите их, обсудите с коллегами из комиссии и решите, готовы ли вы одобрить этот проект."

![2](https://user-images.githubusercontent.com/46641854/69418468-c8181e00-0d2b-11ea-868b-e468bcb676fe.jpg)
![1](https://user-images.githubusercontent.com/46641854/69418471-cb130e80-0d2b-11ea-9e15-cc6921de9452.jpg)

**Comment by DenMesh** [comment]
(Заметки себе, чтобы не забыть)
1 пропускаю (будет изменена концепция)
3 исправлено
4 исправлено

**Comment by DenMesh** [comment]
(заметки себе, продолжение)
6 исправлено
7 не могу воспроизвести
8 исправлено

**Comment by DenMesh** [comment]
(заметки себе, продолжение-2)
5 исправлено

**Comment by everdina** [comment]
в дополнение к п.2

![отступы кнопко и тп](https://user-images.githubusercontent.com/46641854/69866954-8c92cc00-12b6-11ea-93ec-f7e39c9c3504.jpg)
