### ISSUE TITLE
дизайн: добавить значек загрузки

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#72]
значок загрузки, который показывать, пока вся страница не загрузится целиком
И его же рядом с надписью "Подождите, игра начинается", "Ждем завершения хода"
![sprites-preloader](https://user-images.githubusercontent.com/46641854/69420627-14fdf380-0d30-11ea-9f96-1ec92053015e.png)

**Comment by DenMesh** [comment]
Добавлен
