### ISSUE TITLE
[Комиссия] Тексты правил

### ISSUE THREAD

**Issue by DenMesh** [DenMesh/stem-project-issues#73]
@kupaeva Нужны правила для ролей в комиссии. Формат .pdf.

**Comment by kupaeva** [comment]
пн, 25 нояб. 2019 г. в 17:57, DenMesh <notifications@github.com>:

**Comment by DenMesh** [comment]
Нет, если ты пыталась что-то сюда ответить, у тебя не получилось(

**Comment by kupaeva** [comment]
[врач_телефон.pdf](https://github.com/DenMesh/stem-project-issues/files/3913081/_.pdf)
[ученый_телефон.pdf](https://github.com/DenMesh/stem-project-issues/files/3913082/_.pdf)
[Uploading общественный деятель_телефон.pdf…]()
[Uploading юрист_телефон.pdf…]()

**Comment by DenMesh** [comment]
Ок, давайте попробуем ещё раз. Общественный деятель и юрист не подгрузились - раз. Если есть возможность, **не называйте файлы русскими буквами**, два. И три, что делать, если у клиента телефон не по размеру страницы, которая выбрана? И да, проверь пробелы - например, у врача в подсчёте очков нет пробела между "получает" и "4 очка".

**Comment by kupaeva** [comment]
[lawyer_phone.pdf](https://github.com/DenMesh/stem-project-issues/files/3913190/lawyer_phone.pdf)
[scientist_phone.pdf](https://github.com/DenMesh/stem-project-issues/files/3913191/scientist_phone.pdf)
[society_phone.pdf](https://github.com/DenMesh/stem-project-issues/files/3913192/society_phone.pdf)
[doctor_phone.pdf](https://github.com/DenMesh/stem-project-issues/files/3913193/doctor_phone.pdf)

3) они будут скрулить. Это нормально. Принципиально, что строчки короткие, не нужно сдвигать экран, чтобы прочитать строку.

**Comment by DenMesh** [comment]
Принято.02.12.2019, 23:34, "kupaeva" <notifications@github.com>:lawyer_phone.pdf
scientist_phone.pdf
society_phone.pdf
doctor_phone.pdf

они будут скрулить. Это нормально. Принципиально, что строчки короткие, не нужно сдвигать экран, чтобы прочитать строку.

**Comment by DenMesh** [comment]
Правила подгружены
