### ISSUE TITLE
[Комиссия по этике] [Возможная ловушка для пользователя]

### ISSUE THREAD

**Issue by everdina** [DenMesh/stem-project-issues#79]
**Баг**

я только что случайно жамкнула на кнопку "Начать следующий этап" на экране для проектора два раза подряд, потому что мне показалось, что она не нажалась в первый раз. Подозреваю, такое может произойти и у пользователя. Соответственно, потерян ход.

**Предложение изменения или добавления**

Давайте при нажатии менять эту кнопку на надпись типа "Убедитесь, что команды получили новое задание в своих интерфейсах" и ниже кнопка. Вариант: кнопка ниже появляется через 10 секунд.

**Comment by DenMesh** [comment]
Кнопка "начать следующий этап" нажимается раз в полсекунды, не чаще.29.11.2019, 14:00, "everdina" <notifications@github.com>:Баг
я только что случайно жамкнула на кнопку "Начать следующий этап" на экране для проектора два раза подряд, потому что мне показалось, что она не нажалась в первый раз. Подозреваю, такое может произойти и у пользователя.
Предложение изменения или добавления
Давайте при нажатии менять эту кнопку на надпись типа "Убедитесь, что команды получили новое задание в своих интерфейсах" и ниже кнопка. Вариант: кнопка ниже появляется через 10 секунд.

**Comment by DenMesh** [comment]
Про надпись - когда она появляется, когда она пропадает? Появляющаяся/исчезающая кнопка, ИМХО, не очень хорошо, пользователь может успеть возопить от того, что у него кнопку украли.29.11.2019, 14:00, "everdina" <notifications@github.com>:Баг
я только что случайно жамкнула на кнопку "Начать следующий этап" на экране для проектора два раза подряд, потому что мне показалось, что она не нажалась в первый раз. Подозреваю, такое может произойти и у пользователя.
Предложение изменения или добавления
Давайте при нажатии менять эту кнопку на надпись типа "Убедитесь, что команды получили новое задание в своих интерфейсах" и ниже кнопка. Вариант: кнопка ниже появляется через 10 секунд.

**Comment by everdina** [comment]
Еще вариант: когда пользователь нажал, заливать экран белым прозрачностью 50%, на нем давать  наш индикатор загрузки и надпись "Загружается следующий шаг" на две секунды. Это как бы такая отмашка между этапами, ясно видимая, не спутаешь и не возопишь:)
