### ISSUE TITLE
Корпоративные ценности пожелания

### ISSUE THREAD

**Issue by mizerkal** [DenMesh/stem-project-issues#95]
Не баги, но пожелания по визуалу, если что-то из этого супер сложное - можно не делать:

1) Задача блокировщик - не только название, но и из какого отдела
2) Задачи разных периодов выделять разными цветами

**Comment by DenMesh** [comment]
@everdina, можешь подобрать цвета к пункту 2?

**Comment by everdina** [comment]
![задачи разных периодов выделять разными цветами](https://user-images.githubusercontent.com/46641854/74846067-f3b59f00-5340-11ea-8ec1-7b8f690fb779.jpg)
цвет шрифта - такой же красный, как везде и bold
цвет фона - #f8c9e4
